spring:
  application:
    name: "runnerz"
  datasource:
    url: "jdbc:postgresql://localhost:5432/runnerz"
    username: "myuser"
    password: "KoXH5if29kLu5dSvdY"
    driver-class-name: org.postgresql.Driver
  sql:
    init:
      mode: always
#spring.sql.init.mode=always
#spring.h2.console.enabled=true
#spring.datasource.generate-unique-name=false

